module.exports = {
  trailingComma: 'es5',
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'css',
  proseWrap: 'preserve',
  arrowParens: 'avoid',
  tabWidth: 2,
  printWidth: 100,
  semi: true,
  singleQuote: true,
  bracketSpacing: true,
  bracketSameLine: true,
  useTabs: false,
  experimentalTernaries: false,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
  proseWrap: 'always',
  requirePragma: false,
  insertPragma: false,
};
