name: CI

on:
  push:
    branches: ["main"]

jobs:
  stratRelease:
    if: "github.event.repository.fork == false"
    name: Release Codefend App
    uses: ./.github/workflows/Release.yml
    secrets: inherit
